language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# command to run tests
script:
  - pytest
  - coverage run manage.py test
  - coverage report -m --skip-covered --omit="*/travis*"
  - coverage html
  - coverage html --omit="*/travis*"
after_success:
  - coveralls