language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - ENV_VAR=testing

# create test db
before_script:
  - psql -c 'create database test_weconnect_db;' -U postgres

# command to run tests
script:
  - pytest
  - coverage run --source='.' --omit='run.py' manage.py test
  - coverage report

# generate code climate report
after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls