language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# command to run tests
script:
  - pytest
  - coverage run manage.py test
  - coverage report
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_script: cat ./coverage/lcov.info
after_success:
  - coveralls