language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# command to run tests
script:
  - pytest --cov-report term --cov=app
  # - coverage run manage.py test
  # - coverage report -m
  # - coverage html
after_success:
  - coveralls