language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

# for codecoverage on codeclimate.com
env:
  global:
  - ENV_VAR=testing

# command to run tests
script:
  - pytest
  - coverage run manage.py test
  - coverage report
after_script:
  - codeclimate-test-reporter
after_success:
  - coveralls