language: python
python:
  - "3.6"

# command to install dependencies
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - pip install -r requirements.txt

# for codecoverage on codeclimate.com
env:
  global:
    - CC_TEST_REPORTER_ID=b1291fa23eaa46259ebf81dedc73ffb661fc2bc3d67378004cef34bf375ad739
  - ENV_VAR=testing

# command to run tests
script:
  - pytest
  - coverage run manage.py test
  - coverage report
after_success:
  - coveralls