language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

# configure os environment variables
env:
  - SECRET_KEY=some_secret_value FLASK_CONFIG=testing

# command to run tests
script:
  - pytest
  - coverage run --source='.' --omit='run.py' manage.py test
  - coverage report

# generate code climate report
after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls
