version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
          FLASK_CONFIG: testing
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_weconnect_db
          POSTGRES_PASSWORD: ""
    steps:    
      - checkout
      - run: mkdir test-reports
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
