version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          DATABASE_URL: postgresql://db_user:password@localhost/test_weconnect_db
          FLASK_CONFIG: testing
      - image: circleci/postgres:10.1

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: set database
          command: |
            psql -p 5433 -c "create database test_weconnect_db;"

      - run:
          name: set db user
          command: |
            psql -p 5433 -c "create user db_user with password 'password';"

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
